apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  01-init-multiple-dbs.sql: |
    CREATE DATABASE dbuser;
    --CREATE DATABASE dbfinancialevaluation;
    --CREATE DATABASE dbcredit;
    --CREATE DATABASE dbdocument;
